# Generated by Django 3.1.2 on 2020-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201007_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Back'),
        ),
    ]
