# Generated by Django 3.1.2 on 2020-10-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201007_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Enter a brief bio of the author', max_length=1000, null=True),
        ),
    ]
