# Generated by Django 3.1.2 on 2020-10-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['-due_back_date'], 'permissions': (('can_mark_returned', 'Set the book as returned'),)},
        ),
    ]
